name: 🕵️‍♂️ Test smart contracts

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
        python_version:
          - 3.14

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Vyper
        run: pip install vyper==0.3.10

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry tests
        run: forge test
        env:
          FOUNDRY_PROFILE: ci
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
